### ISSUE TITLE
Console being flooded

### ISSUE THREAD

**Issue by NoMansLand-MFGC** [Nosmakos/DeadSociety#2]
Hey Nosmakos,

Looking forward to using this one :) I get most of it but my console floods me with:

```
[0 10:10:25 ERROR]: Could not pass event CreatureSpawnEvent to DeadSociety v6.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:446) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:383) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.World.addEntity(World.java:907) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:917) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.SpawnerCreature.a(SpawnerCreature.java:182) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:260) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

```
means no zombies will spawn and makes playing a bit harder

**Comment by NoMansLand-MFGC** [comment]
Loading: 

[0 10:21:40 INFO]: [DeadSociety] Enabling DeadSociety v6.6
[0 10:21:40 INFO]: [DeadSociety] Could not disable example1. Unknown world found - Ignoring...
[0 10:21:40 INFO]: [DeadSociety] Loaded - [Vault Economy: true | Disabled Worlds: 1 | Users Data: 1 | Zombies Data: 0 | Lootable Chests: 0 | Zones: 0]


---

After a player joins:

g.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:446) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:383) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.World.addEntity(World.java:907) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:917) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.SpawnerCreature.a(SpawnerCreature.java:182) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:260) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftEntityEquipment.setArmorContents(CraftEntityEquipment.java:92) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at me.nosmastew.deadsociety.zombies.ZombieHandlers.onSpawn(ZombieHandlers.java:83) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        ... 14 more
[0 10:22:32 ERROR]: Could not pass event CreatureSpawnEvent to DeadSociety v6.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:446) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:383) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.World.addEntity(World.java:907) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:917) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.SpawnerCreature.a(SpawnerCreature.java:182) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:260) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-e6eb36f-d65a257]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftEntityEquipment.setArmorContents(CraftEntityEquipment.java:92) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        at me.nosmastew.deadsociety.zombies.ZombieHandlers.onSpawn(ZombieHandlers.java:83) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot.jar:git-Spigot-e6eb36f-d65a257]
        ... 14 more
[0 10:22:32 ERROR]: Could not pass event CreatureSpawnEvent to DeadSociety v6.6

**Comment by Nosmakos** [comment]
Solved! 6.6.1 update.
